name: 'Deploy to AKS with Helm'
description: 'Deploys an app to AKS using Helm'
inputs:
  acr_name:
    description: 'Azure Container Registry name'
    required: true
    type: string
  image_name:
    description: 'Name of the Docker image'
    required: true
    type: string
  image_tag:
    description: 'Tag for the Docker image'
    required: true
    type: string
  arm_client_id:
    description: 'Azure Client ID'
    required: true
    type: string
  arm_client_secret:
    description: 'Azure Client Secret'
    required: true
    type: string
  arm_tenant_id:
    description: 'Azure Tenant ID'
    required: true
    type: string
  arm_subscription_id:
    description: 'Azure Subscription ID'
    required: true
    type: string
  aks_resource_group:
    description: 'Azure Resource Group of AKS'
    required: true
    type: string
  aks_cluster_name:
    description: 'Azure AKS Cluster Name'
    required: true
    type: string
  helm_chart_path:
    description: 'Path to Helm chart directory'
    required: true
    type: string
  acr_secret_name:
    description: 'Secret acr name'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Print input values
      run: |
        echo "Helm path: ${{ inputs.helm_chart_path }}"
      shell: bash
    - name: Login to Azure with Service Principal
      run: |
        az login --service-principal \
          -u ${{ inputs.arm_client_id }} \
          -p ${{ inputs.arm_client_secret }} \
          --tenant ${{ inputs.arm_tenant_id }}
      shell: bash
  
    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ inputs.aks_resource_group }} --name ${{ inputs.aks_cluster_name }}
      shell: bash
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      shell: bash
    # - name: Delete Helm
    #   run: |
    #     kubectl delete svc backend-service -n default
    #     kubectl delete deploy backend-app -n default
    #   shell: bash

    - name: Deploy with Helm
      run: |
        helm upgrade --install ${GITHUB_SHA} ./manifests/backend \
        --namespace default \
        --set "image.repository=${{ inputs.acr_name }}.azurecr.io/${{ inputs.image_name }}" \
        --set "image.tag=${{ inputs.image_tag }}" \
        --set "image.pullSecret=${{ inputs.acr_secret_name }}" \
      shell: bash
