name: CI CD Pipeline

on:
  push:
    branches:
      - main  
  workflow_dispatch:
jobs:
  extract_version:
    runs-on: ubuntu-latest
    outputs:
      NEW_VERSION: ${{ steps.extract_version.outputs.NEW_VERSION }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up script permissions
        run: |
          chmod +x ./extract_version.sh
          chmod +x ./upload_version.sh

      - id : extract_version 
        name: Extract and increment version
        run: |
          NEW_VERSION=$(./extract_version.sh)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Upload version into file
        run: |
          ./upload_version.sh "$NEW_VERSION"

  # testing:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - extract_version
  #   environment: Production
  #   if: github.ref == 'refs/heads/main'
  #   steps: 
 # 
  #     - name: Check out repository
  #       uses: actions/checkout@v3
  #     
  #     - name: Install package and dependencies
  #       run: |
  #         sudo apt install npm -y 
  #         sudo npm install --save-dev @vue/cli-service
 # 
  #     - name: Do testing on component
  #       run: |
  #         npm run test:unit
    
  # call_frontend_ci:
  #   needs: 
  #     - extract_version
  #     # - testing
  #   uses: stemdo-labs/final-project-exercise-javierrochadev/.github/workflows/frontend-CI.yaml@main
  #   with:
  #     image_tag: "${{ needs.extract_version.outputs.NEW_VERSION }}" 
  #     image_name: "myapp-frontend"
  #     release_env: ${{ github.ref == 'refs/heads/main' && 'pro' || 'dev' }}
  #     release_name: "frontend"
  #   secrets:
  #     acr_name: ${{ secrets.ACR_NAME }}
  #     arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
  #     arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
  #     arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
 
  call_frontend_cd:
    needs:
      - extract_version
      # - call_frontend_ci
    uses: stemdo-labs/final-project-exercise-javierrochadev/.github/workflows/frontend-CD.yaml@main
    with:
      image_name: "myapp-frontend"
      chart_name: "frontend"
      release_env: ${{ github.ref == 'refs/heads/main' && 'pro' || 'dev' }}
      image_tag: "${{ needs.extract_version.outputs.NEW_VERSION }}" 
      namespace: "${{ vars.NAMESPACE }}"
    secrets:
      acr_name: ${{ secrets.ACR_NAME }}
      arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
      arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
      arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      aks_resource_group: ${{ secrets.RESOURCE_GROUP_NAME }}
      aks_cluster_name: ${{ secrets.AKS_NAME }}
      acr_secret_name: ${{ secrets.ACR_SECRET_NAME }}
      harbor_username: ${{ secrets.HARBOR_USER }}
      harbor_password: ${{ secrets.HARBOR_PASS }}
      harbor_ip: ${{ secrets.HARBOR_IP }}

     
