# .github/workflows/main-deploy.yaml
name: Main Deployment Workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # - name: Usar la acción para extraer la versión
      #   uses: ./.github/actions/extract-version
      #   id: extract_version
      #   with:
      #     file: '/pom.xml'

      # - name: Imprimir la versión extraída
      #   id: show_version
      #   run: echo "La versión es: ${{ steps.extract_version.outputs.version }}"

      # - name: Build and Push Docker Image
      #   uses: ./.github/actions/upload_image
      #   with:
      #     acr_name: ${{ secrets.ACR_NAME }}
      #     image_name: "myapp-frontend"
      #     image_tag: "4.0.0"
      #     arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
      #     arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
      #     arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}

      - name: Upload an image 
        uses: ./.github/actions/deploy
        with:
          acr_name: ${{ secrets.ACR_NAME }}
          image_name: "myapp-frontend"
          image_tag: "4.0.0"
          arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
          arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
          arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
          aks_resource_group: ${{ secrets.RESOURCE_GROUP_NAME }}
          aks_cluster_name: ${{ secrets.AKS_NAME }}
          acr_secret_name: ${{ secrets.ACR_SECRET_NAME }}
          helm_chart_path: "./manifest/backend"
          
