name: Main Deployment Workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: runner-stemdo-labs

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up script permissions
        run: |
          chmod +x ./extract_version.sh
          chmod +x ./upload_version.sh

      - name: Extract and increment version
        id: extract_version
        run: |
          NEW_VERSION=$(./extract_version.sh)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Upload version into file
        run: |
          ./upload_version.sh "$NEW_VERSION"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ACR_NAME }}/myapp-frontend:${{ env.NEW_VERSION }}

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install frontend ./charts/frontend \
          --namespace default \
          --set image.repository=${{ secrets.ACR_NAME }}/myapp-frontend \
          --set image.tag=${{ env.NEW_VERSION }} \
          --set acr.username=${{ secrets.HARBOR_USER }} \
          --set acr.password=${{ secrets.HARBOR_PASS }} \
          --set acr.server=${{ secrets.HARBOR_IP }} \
          --set acr.secretName=${{ secrets.ACR_SECRET_NAME }} \
          --set aks.clusterName=${{ secrets.AKS_NAME }} \
          --set aks.resourceGroup=${{ secrets.RESOURCE_GROUP_NAME }} \
          --set nodeSelector.kubernetes.io/os=linux

